// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIYK-YE-KDmt6f31cG7sEdkSRuCxGsWQ',
    appId: '1:1036631160537:web:2016a8e48bcea3cc44b0c8',
    messagingSenderId: '1036631160537',
    projectId: 'munchbites-8d436',
    authDomain: 'munchbites-8d436.firebaseapp.com',
    storageBucket: 'munchbites-8d436.firebasestorage.app',
    measurementId: 'G-1VWRRVBQYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJClPSeVrtm-Dl3-F__eiSdvs5gskq5Dg',
    appId: '1:1036631160537:android:899ee540c800202444b0c8',
    messagingSenderId: '1036631160537',
    projectId: 'munchbites-8d436',
    storageBucket: 'munchbites-8d436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHcvQ-dnuuZiK2k0kXCrBVoltswncfi1M',
    appId: '1:1036631160537:ios:42d13e0bf756976244b0c8',
    messagingSenderId: '1036631160537',
    projectId: 'munchbites-8d436',
    storageBucket: 'munchbites-8d436.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHcvQ-dnuuZiK2k0kXCrBVoltswncfi1M',
    appId: '1:1036631160537:ios:42d13e0bf756976244b0c8',
    messagingSenderId: '1036631160537',
    projectId: 'munchbites-8d436',
    storageBucket: 'munchbites-8d436.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIYK-YE-KDmt6f31cG7sEdkSRuCxGsWQ',
    appId: '1:1036631160537:web:66a063f2b7c4cad744b0c8',
    messagingSenderId: '1036631160537',
    projectId: 'munchbites-8d436',
    authDomain: 'munchbites-8d436.firebaseapp.com',
    storageBucket: 'munchbites-8d436.firebasestorage.app',
    measurementId: 'G-4HW3T72DTM',
  );
}
